name: JS tests
on: [push]
jobs:
  js-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache JS dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
    - name: Install JS dependencies
      run: yarn
    - name: Check for JS package vulnerabilities
      run: yarn audit
